// flow-typed signature: 8cb47b713d594fc428f3e19fa2208fdc
// flow-typed version: <<STUB>>/pdf2json_v^1.2.3/flow_v0.153.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdf2json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdf2json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdf2json/base/core/bidi' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/charsets' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/chunked_stream' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/cidmaps' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/cmap' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/core' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/crypto' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/evaluator' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/font_renderer' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/fonts' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/glyphlist' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/image' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/jbig2' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/jpg' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/jpx' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/metrics' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/network' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/obj' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/parser' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/pdf_manager' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/stream' {
  declare module.exports: any;
}

declare module 'pdf2json/base/core/worker' {
  declare module.exports: any;
}

declare module 'pdf2json/base/display/api' {
  declare module.exports: any;
}

declare module 'pdf2json/base/display/canvas' {
  declare module.exports: any;
}

declare module 'pdf2json/base/display/font_loader' {
  declare module.exports: any;
}

declare module 'pdf2json/base/display/metadata' {
  declare module.exports: any;
}

declare module 'pdf2json/base/shared/annotation' {
  declare module.exports: any;
}

declare module 'pdf2json/base/shared/cffStandardStrings' {
  declare module.exports: any;
}

declare module 'pdf2json/base/shared/colorspace' {
  declare module.exports: any;
}

declare module 'pdf2json/base/shared/fonts_utils' {
  declare module.exports: any;
}

declare module 'pdf2json/base/shared/function' {
  declare module.exports: any;
}

declare module 'pdf2json/base/shared/pattern' {
  declare module.exports: any;
}

declare module 'pdf2json/base/shared/util' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/p2jcmd' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdf' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdfanno' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdfcanvas' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdffield' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdffill' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdffont' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdfimage' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdfline' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/pdfunit' {
  declare module.exports: any;
}

declare module 'pdf2json/lib/ptixmlinject' {
  declare module.exports: any;
}

declare module 'pdf2json/pdf2json' {
  declare module.exports: any;
}

declare module 'pdf2json/pdfparser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdf2json/base/core/bidi.js' {
  declare module.exports: $Exports<'pdf2json/base/core/bidi'>;
}
declare module 'pdf2json/base/core/charsets.js' {
  declare module.exports: $Exports<'pdf2json/base/core/charsets'>;
}
declare module 'pdf2json/base/core/chunked_stream.js' {
  declare module.exports: $Exports<'pdf2json/base/core/chunked_stream'>;
}
declare module 'pdf2json/base/core/cidmaps.js' {
  declare module.exports: $Exports<'pdf2json/base/core/cidmaps'>;
}
declare module 'pdf2json/base/core/cmap.js' {
  declare module.exports: $Exports<'pdf2json/base/core/cmap'>;
}
declare module 'pdf2json/base/core/core.js' {
  declare module.exports: $Exports<'pdf2json/base/core/core'>;
}
declare module 'pdf2json/base/core/crypto.js' {
  declare module.exports: $Exports<'pdf2json/base/core/crypto'>;
}
declare module 'pdf2json/base/core/evaluator.js' {
  declare module.exports: $Exports<'pdf2json/base/core/evaluator'>;
}
declare module 'pdf2json/base/core/font_renderer.js' {
  declare module.exports: $Exports<'pdf2json/base/core/font_renderer'>;
}
declare module 'pdf2json/base/core/fonts.js' {
  declare module.exports: $Exports<'pdf2json/base/core/fonts'>;
}
declare module 'pdf2json/base/core/glyphlist.js' {
  declare module.exports: $Exports<'pdf2json/base/core/glyphlist'>;
}
declare module 'pdf2json/base/core/image.js' {
  declare module.exports: $Exports<'pdf2json/base/core/image'>;
}
declare module 'pdf2json/base/core/jbig2.js' {
  declare module.exports: $Exports<'pdf2json/base/core/jbig2'>;
}
declare module 'pdf2json/base/core/jpg.js' {
  declare module.exports: $Exports<'pdf2json/base/core/jpg'>;
}
declare module 'pdf2json/base/core/jpx.js' {
  declare module.exports: $Exports<'pdf2json/base/core/jpx'>;
}
declare module 'pdf2json/base/core/metrics.js' {
  declare module.exports: $Exports<'pdf2json/base/core/metrics'>;
}
declare module 'pdf2json/base/core/network.js' {
  declare module.exports: $Exports<'pdf2json/base/core/network'>;
}
declare module 'pdf2json/base/core/obj.js' {
  declare module.exports: $Exports<'pdf2json/base/core/obj'>;
}
declare module 'pdf2json/base/core/parser.js' {
  declare module.exports: $Exports<'pdf2json/base/core/parser'>;
}
declare module 'pdf2json/base/core/pdf_manager.js' {
  declare module.exports: $Exports<'pdf2json/base/core/pdf_manager'>;
}
declare module 'pdf2json/base/core/stream.js' {
  declare module.exports: $Exports<'pdf2json/base/core/stream'>;
}
declare module 'pdf2json/base/core/worker.js' {
  declare module.exports: $Exports<'pdf2json/base/core/worker'>;
}
declare module 'pdf2json/base/display/api.js' {
  declare module.exports: $Exports<'pdf2json/base/display/api'>;
}
declare module 'pdf2json/base/display/canvas.js' {
  declare module.exports: $Exports<'pdf2json/base/display/canvas'>;
}
declare module 'pdf2json/base/display/font_loader.js' {
  declare module.exports: $Exports<'pdf2json/base/display/font_loader'>;
}
declare module 'pdf2json/base/display/metadata.js' {
  declare module.exports: $Exports<'pdf2json/base/display/metadata'>;
}
declare module 'pdf2json/base/shared/annotation.js' {
  declare module.exports: $Exports<'pdf2json/base/shared/annotation'>;
}
declare module 'pdf2json/base/shared/cffStandardStrings.js' {
  declare module.exports: $Exports<'pdf2json/base/shared/cffStandardStrings'>;
}
declare module 'pdf2json/base/shared/colorspace.js' {
  declare module.exports: $Exports<'pdf2json/base/shared/colorspace'>;
}
declare module 'pdf2json/base/shared/fonts_utils.js' {
  declare module.exports: $Exports<'pdf2json/base/shared/fonts_utils'>;
}
declare module 'pdf2json/base/shared/function.js' {
  declare module.exports: $Exports<'pdf2json/base/shared/function'>;
}
declare module 'pdf2json/base/shared/pattern.js' {
  declare module.exports: $Exports<'pdf2json/base/shared/pattern'>;
}
declare module 'pdf2json/base/shared/util.js' {
  declare module.exports: $Exports<'pdf2json/base/shared/util'>;
}
declare module 'pdf2json/lib/p2jcmd.js' {
  declare module.exports: $Exports<'pdf2json/lib/p2jcmd'>;
}
declare module 'pdf2json/lib/pdf.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdf'>;
}
declare module 'pdf2json/lib/pdfanno.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdfanno'>;
}
declare module 'pdf2json/lib/pdfcanvas.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdfcanvas'>;
}
declare module 'pdf2json/lib/pdffield.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdffield'>;
}
declare module 'pdf2json/lib/pdffill.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdffill'>;
}
declare module 'pdf2json/lib/pdffont.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdffont'>;
}
declare module 'pdf2json/lib/pdfimage.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdfimage'>;
}
declare module 'pdf2json/lib/pdfline.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdfline'>;
}
declare module 'pdf2json/lib/pdfunit.js' {
  declare module.exports: $Exports<'pdf2json/lib/pdfunit'>;
}
declare module 'pdf2json/lib/ptixmlinject.js' {
  declare module.exports: $Exports<'pdf2json/lib/ptixmlinject'>;
}
declare module 'pdf2json/pdf2json.js' {
  declare module.exports: $Exports<'pdf2json/pdf2json'>;
}
declare module 'pdf2json/pdfparser.js' {
  declare module.exports: $Exports<'pdf2json/pdfparser'>;
}
